project_id = "irdlyshhtwzqjvymilww"

[functions.scan-llm]
verify_jwt = true

[[functions]]
name = "analyze-vulnerability"
verify_jwt = true

[[functions]]
name = "augment-prompt"
verify_jwt = true

[[functions]]
name = "generate-dataset"
verify_jwt = true